AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Back end of visitor counter.

Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTION,GET'"
      AllowHeaders: "'*'"
  Function:
    Timeout: 3

Parameters:
  DynamoDBTableName:
    Description: 'The name of the DynamoDB table for the visitor count'
    Type: String
Resources:
  # DynamoDB
  DDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref DynamoDBTableName
      PrimaryKey:
        Name: id
        Type: String

  # Lambda IAM role to access DynamoDB
  VisitorCounterFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DDBTable}'
              - Effect: Allow
                Action:
                  - logs:*
                Resource: '*'

  # Lambda Function
  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: visitor_count.lambda_handler
      Runtime: python3.8
      Role: !GetAtt VisitorCounterFunctionRole.Arn
      Environment:
        Variables:
          databaseName: !Ref DDBTable
      Events:
        VisitorCounter:
          Type: Api
          Properties:
            Path: /visitor-count
            Method: GET

Outputs:
  # API Gateway
  VisitorCountApi:
    # Type: AWS::ApiGateway::Deployment
    # Properties:
    #   RestApiId: !Ref MyApi
    Description:
      API Gateway endpoint URL
      # StageName: Prod
      # Cors:
      #   AllowMethods: 'POST, GET, OPTIONS'
      #   AllowHeaders: 'X-Forwarded-For, Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With'
      #   AllowOrigin: '*'
      #   MaxAge: '600'
      #   AllowCredentials: True
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor-count/'
  VisitorCountFunction:
    Description: Lambda function ARN
    Value: !GetAtt VisitorCountFunction.Arn
  VisitorCounterFunctionRole:
    Description: IAM role created for Lambda function
    Value: !GetAtt VisitorCounterFunctionRole.Arn
  DDBTable:
    Description: DynamoDB table to store visitor count
    Value: !GetAtt DDBTable.Arn
